<?xml version="1.0" encoding="utf-8"?><Database Name="nature-net-aces" Class="TableTopDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=nature-net-aces;Integrated Security=True" SettingsObjectName="sync.Properties.Settings" SettingsPropertyName="nature_netConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Action_Type" Member="Action_Types">
    <Type Name="Action_Type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Action_Type_Action" Member="Actions" ThisKey="id" OtherKey="type_id" Type="Action" />
    </Type>
  </Table>
  <Table Name="dbo.Activity" Member="Activities">
    <Type Name="Activity">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="creation_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="expire_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Activity_Collection" Member="Collections" ThisKey="id" OtherKey="activity_id" Type="Collection" />
      <Association Name="Location_Activity" Member="Location" ThisKey="location_id" OtherKey="id" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Collection" Member="Collections">
    <Type Name="Collection">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="activity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Collection_Collection_Contribution_Mapping" Member="Collection_Contribution_Mappings" ThisKey="id" OtherKey="collection_id" Type="Collection_Contribution_Mapping" />
      <Association Name="Activity_Collection" Member="Activity" ThisKey="activity_id" OtherKey="id" Type="Activity" IsForeignKey="true" />
      <Association Name="User_Collection" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Collection_Contribution_Mapping" Member="Collection_Contribution_Mappings">
    <Type Name="Collection_Contribution_Mapping">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="contribution_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="collection_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Collection_Collection_Contribution_Mapping" Member="Collection" ThisKey="collection_id" OtherKey="id" Type="Collection" IsForeignKey="true" />
      <Association Name="Contribution_Collection_Contribution_Mapping" Member="Contribution" ThisKey="contribution_id" OtherKey="id" Type="Contribution" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contribution" Member="Contributions">
    <Type Name="Contribution">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="media_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Contribution_Collection_Contribution_Mapping" Member="Collection_Contribution_Mappings" ThisKey="id" OtherKey="contribution_id" Type="Collection_Contribution_Mapping" />
      <Association Name="Location_Contribution" Member="Location" ThisKey="location_id" OtherKey="id" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="object_type" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="object" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="object_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Feedback_Feedback" Member="Feedbacks" ThisKey="id" OtherKey="parent_id" Type="Feedback" />
      <Association Name="Feedback_Feedback" Member="Feedback1" ThisKey="parent_id" OtherKey="id" Type="Feedback" IsForeignKey="true" />
      <Association Name="Feedback_Type_Feedback" Member="Feedback_Type" ThisKey="type_id" OtherKey="id" Type="Feedback_Type" IsForeignKey="true" />
      <Association Name="User_Feedback" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback_Type" Member="Feedback_Types">
    <Type Name="Feedback_Type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="data_type" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Feedback_Type_Feedback" Member="Feedbacks" ThisKey="id" OtherKey="type_id" Type="Feedback" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Location_Activity" Member="Activities" ThisKey="id" OtherKey="location_id" Type="Activity" />
      <Association Name="Location_Contribution" Member="Contributions" ThisKey="id" OtherKey="location_id" Type="Contribution" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(128)" CanBeNull="true" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Collection" Member="Collections" ThisKey="id" OtherKey="user_id" Type="Collection" />
      <Association Name="User_Feedback" Member="Feedbacks" ThisKey="id" OtherKey="user_id" Type="Feedback" />
      <Association Name="User_Action" Member="Actions" ThisKey="id" OtherKey="user_id" Type="Action" />
    </Type>
  </Table>
  <Table Name="dbo.Design_Ideas" Member="Design_Ideas">
    <Type Name="Design_Idea">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="media_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Action" Member="Actions">
    <Type Name="Action">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="object_type" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Action_Type_Action" Member="Action_Type" ThisKey="type_id" OtherKey="id" Type="Action_Type" IsForeignKey="true" />
      <Association Name="User_Action" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Interaction_Log" Member="Interaction_Logs">
    <Type Name="Interaction_Log">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="touch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="touch_x" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="touch_y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Interaction_Type_Interaction_Log" Member="Interaction_Type" ThisKey="type" OtherKey="id" Type="Interaction_Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Interaction_Type" Member="Interaction_Types">
    <Type Name="Interaction_Type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Interaction_Type_Interaction_Log" Member="Interaction_Logs" ThisKey="id" OtherKey="type" Type="Interaction_Log" />
    </Type>
  </Table>
</Database>